### ISSUE TITLE
Document styling

### ISSUE THREAD

**Issue by philnash** [philnash/astro-components#2]
Styling is currently done with CSS classes, document how this works. 

Consider ways to make it easier to style like other components in Astro.

**Comment by jsnape** [comment]
I had to wrap the control in a div with class="pagination" and do the styling like:

```css
.pagination ul {
    display: inline-flex;
}

.pagination ul li {
    margin-right: 20px;
}
```

but it seems a little clunky. I would love to use tailwind classes instead of custom css.
